volumes:
  mysql_data:
  airflow_postgres_data:
  airflow_data:

networks:
  cbm_airflow_network:
    driver: bridge

x-airflow-common:
  &airflow-common
  image: apache/airflow:latest
  environment:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-pg-db:5432/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW__WEBSERVER__RBAC=True
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW__WEBSERVER__COOKIE_SECURE=False
    - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
    - AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True
    - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=600
    - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
    - AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS=True
    - _PIP_ADDITIONAL_REQUIREMENTS=numpy pandas
    - TZ=UTC
  volumes:
    - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg 
    - ./airflow/dags:/opt/airflow/dags
    - airflow_data:/var/lib/airflow
    - ./:/opt/airflow/code
    - /etc/localtime:/etc/localtime:ro
      
  depends_on:
    airflow-pg-db:
      condition: service_healthy
  networks:
    - cbm_airflow_network


services:

  # PostgreSQL Database for Airflow
  airflow-pg-db:
    image: postgres:latest
    container_name: cbm_airflow_pg_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - cbm_airflow_network

  # Airflow Init
  airflow-init:
    << : *airflow-common
    container_name: cbm_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username cbmteam \
          --firstname CBM \
          --lastname Team \
          --email cbm@example.com \
          --role Admin \
          --password evolife

  # Airflow Scheduler
  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: cbm_airflow_scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # Airflow Webserver
  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    container_name: cbm_airflow_webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully


  # MySQL Database for App
  cbm-app-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: evolife_root_password
      MYSQL_DATABASE: cbm_health_db
      MYSQL_USER: cbmteam
      MYSQL_PASSWORD: evolife
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dtabase/evolife_db_init.sql:/docker-entrypoint-initdb.d/evolife_db_init.sql

  # # App Service
  # app:
  #   build:
  #     context: .
  #     dockerfile: AppDockerfile
  #   environment:
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=root_password
  #     - DB_NAME=app_db
  #   depends_on:
  #     - cbm-app-db
  #   ports:
  #     - "5000:5000"

